# example values
html:
  parser:
    service:
      impl:
        user-agent: HeliontSearchBot
        referrer: google.com

html-parser-service-impl:
  user-agent: HeliontSearchBot
  referrer: google.com

indexing-settings:
  sites:
#    - url: https://www.lenta.ru
#      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?allowPublicKeyRetrieval=true&useSSL=false
    username: postgres
    password: root
#    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&serverTimezone=UTC
#    username: root
#    password: root
  jpa:
#    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
#        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
        connection.autocommit: false
        show-sql: true
        format_sql: true
        jdbc:
          batch_size: 500
    hibernate:
      ddl-auto: update

logging:
  level:
    com.graduation.work.searchwebengine:
      service: WARN
    org:
      springframework:
        jdbc:
          core:
            org.springframework.jdbc.core.JdbcTemplate: debug
            org.springframework.jdbc.core.StatementCreatorUtils: TRACE
      hibernate:
        sql: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
  file:
    name: ${java.io.tmpdir}/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"