# example values
html:
  parser:
    service:
      impl:
        user-agent: HeliontSearchBot
        referrer: google.com

html-parser-service-impl:
  user-agent: HeliontSearchBot
  referrer: google.com

indexing-settings:
  sites:
#    - url: https://www.lenta.ru
#      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&serverTimezone=UTC
    username: root
    password: w8Axcd
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true
        show-sql: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    com.graduation.work.searchwebengine:
      service: WARN
    org:
      hibernate:
        type: trace
  file:
    name: ${java.io.tmpdir}/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"